### ISSUE TITLE
nginx reverse proxy and 'Connection' header

### ISSUE THREAD

**Issue by return42** [asciimoo/filtron#10]
Sorry, my question is more related to nginx, but I haven't found a solution and I know here are nginx users who have already set up filtron behind a nginx reverse proxy ...

In my filtron rules I filter

    "filters": ["Header:Connection=close"],

And in my nginx I have configured a reverse proxy

````nginx
location /searx {
    proxy_set_header   Host             $http_host;
    proxy_set_header   X-Real-IP       $remote_addr;
    proxy_set_header   X-Forwarded-For  $proxy_add_x_forwarded_for;
    proxy_set_header   X-Scheme         $scheme;
    proxy_set_header   X-Script-Name    /searx;

    proxy_pass         http://127.0.0.1:4004/;
}
````

My HTTP client sends a ``Connection keep-alive`` header to nginx but the backend at ``http://127.0.0.1:4004`` does not _see_ this keep-alive header (the filter matches and I have also debuged this).  

I have exactly the same setup configured with Apache where I haven't observed such problems. It seems, that  Apache pass all headers through the proxied service .. why does nginx change the Connection header .. and how can I persuade nginx to pass the header through and keep the connection alive? 

I guess nginx sets 'Connection close' since it does not hold the connection to the upstream .. but I don't have a clue how to configure nginx to be transparent: if clients are setting 'keep alive', then hold the line and if client does not set Connection header, then close the line upstream.

**Comment by dalf** [comment]
https://docs.nginx.com/nginx/admin-guide/web-server/reverse-proxy/#passing-request-headers

> **By default**, NGINX redefines two header fields in proxied requests, “Host” and “Connection”, and eliminates the header fields whose values are empty strings. “Host” is set to the $proxy_host variable, and “Connection” is set to close.

see also https://nginx.org/en/docs/http/ngx_http_proxy_module.html#proxy_set_header

**Comment by return42** [comment]
Thanks for your hints! .. do you know how I can pass through the header value from the client to upstream .. I mean, when I set the header explicit on (or even off):

     proxy_set_header Connection on;

the filter rule is useless.

**Comment by return42** [comment]
I do not have wider experience, but some more thoughts .. 

> By default, NGINX redefines two header fields in proxied requests, “Host” and “Connection”

This make sense, since a keep-alive is a decision that must be made anew at each relay station. By Example, it does not make sense to have 'keep-alive' on a loopback device or on a unix socket.

From a bot-blocker view (filtron) we like to use the keep-alive as one criteria to distinguish bots from normal users.  But from the HTTP point of view it does not make sense to simply pass the keep-alive through. The two requirements are diametrically opposed.

For the Host header, we can use the nginx variable `$host`

    proxy_set_header Host $host;

And as I am writing these lines, a see how simple the solution is :)

     proxy_set_header Connection $connection;

Maybe I should have just turned my mind on first, before posting .. but possibly. someone like me will read it and hopefully this post will help them.
