### ISSUE TITLE
Build static release binary for linux

### ISSUE THREAD

**Issue by patrickpichler** [asciimoo/filtron#11]
Is there a reason why the release binary is not staticly compiled?

**Comment by asciimoo** [comment]
No particular reason.

**Comment by asciimoo** [comment]
Why do you recommend static builds?

**Comment by patrickpichler** [comment]
I'm in the process of seting up an searx instance on alpine. Alpine linux is not using glibc so the binary from the release page won't work.

**Comment by asciimoo** [comment]
Yeah, alpine with musl can be problematic in these cases. As a workaround you can use any solution listed here: https://wiki.alpinelinux.org/wiki/Running_glibc_programs or compile it. In the future I'm going to release static binaries.

**Comment by patrickpichler** [comment]
Yeah I compiled it myself but was curios. Thank you for answering :+1:
