### ISSUE TITLE
[QUESTION] Print log docker image

### ISSUE THREAD

**Issue by Pofilo** [asciimoo/filtron#15]
Hello,

I still have Google issues with searx despites I'm using Filtron.
As @return42 said in https://github.com/searx/searx/issues/729, I want to see the logs to be able to see if there is some more requests to block.

> watch the log for a while and see if questionable requests get through. If so, improve your /etc/filtron/rules.json to block such requests.
> This is what I do when my instance get CAPTCHA from google (had 2 issues in the last 6 month).

However, with the Docker image (setup with https://github.com/searx/searx-docker), I don't find a way to show/enable the logs.
I can see logs printed through the `log.Println()` function but I'm not familiar enough with go to understand how to setup/enable/show the logs of all requests (if there is a way to see them).

Otherwise, I could enable the logs of my proxy (traefik and not caddy) to see all requests (that's easy to do and this is maybe the right way).

Thanks for your help (and correct me if I should just enable the logs of my proxy) :)

**Comment by dalf** [comment]
I don't know if a rule like this works:
```
{
    "name": "log",
    "stop": false,
    "actions": [
        {"name": "log",
         "params": {"destination": "stderr"}},
     ]
}
```

But looking at the traefik logs will most probably be easier.

**Comment by Pofilo** [comment]
Thanks, this rule does the work :) (just a little comma to remove after stderr to produce a "valid" json)

It is equivalent than the traefik logs except that I don't have to touch anything on the proxy in production so I prefer.
