### ISSUE TITLE
Whitelist an IP or IP Range

### ISSUE THREAD

**Issue by JacobOkanta** [asciimoo/filtron#17]
I am running Filtron in front of a Searx instance, with the recommended rules [here.](https://raw.githubusercontent.com/searx/searx-docker/7ad4d4903d0ce41de4094d5fe0fecda156b41eaa/rules.json) The problem is that if I do a search from any computer on my network I am presented with "Rate limit exceeded". I believe this is because all of the requests from within my network show as coming from my router, but I can't seem to figure out how to whitelist. Apologies if I'm wrong or this has been asked before, I tried checking issue requests first but couldn't find anything relevant.

**Comment by asciimoo** [comment]
You can add a wrapper rule that does not match to your whitelistable ips, like:
```
{
    "name": "search request",
    "filters": ["!IP=127.0.0.1"],
    "interval": 60,
    "limit": 5000,
    "actions": [
        {"name": "log"}
    ],
    "subrules": [
...
])

```
