### ISSUE TITLE
[Feature Request] add dummy action

### ISSUE THREAD

**Issue by mrpaulblack** [asciimoo/filtron#20]
A dummy action could be useful for when the user wants to whitelist something. For example in https://github.com/paulgoio/filtron/blob/main/src/rules.json#L9 I am allowing the /image_proxy path and stop after that (So that the internal image proxy does not get rate limited by the rule following). I would like to just stop there without logging and have the rest underneath apply to everything except the /image_proxy path. A dummy action, that does nothing, could be the solution.

Maybe this can be implemented by adding a new case at: https://github.com/asciimoo/filtron/blob/master/action/action.go#L45 ?

**Comment by dalf** [comment]
see #21
