### ISSUE TITLE
No installation, cannot convert d.window (type []byte) to type *[32768]byte

### ISSUE THREAD

**Issue by pyrenaica** [asciimoo/filtron#24]
`$GOPATH` Is set up correctly at `/usr/local/filtron/go-apps` but when running `go get github.com/asciimoo/filtron` i get the following output:

```
# github.com/klauspost/compress/flate
go-apps/src/github.com/klauspost/compress/flate/deflate.go:135:23: cannot convert d.window (type []byte) to type *[32768]byte
go-apps/src/github.com/klauspost/compress/flate/deflate.go:135:56: cannot convert d.window[windowSize:] (type []byte) to type *[32768]byte
go-apps/src/github.com/klauspost/compress/flate/fast_encoder.go:93:28: cannot convert e.hist (type []byte) to type *[32768]byte
go-apps/src/github.com/klauspost/compress/flate/fast_encoder.go:93:63: cannot convert e.hist[offset:] (type []byte) to type *[32768]byte
go-apps/src/github.com/klauspost/compress/flate/huffman_bit_writer.go:794:17: cannot convert w.literalFreq[:] (type []uint16) to type *[256]uint16
go-apps/src/github.com/klauspost/compress/flate/huffman_bit_writer.go:796:16: cannot convert w.literalFreq[256:] (type []uint16) to type *[32]uint16

```

I verified in `/usr/local/filtron/go-apps` and there is no `bin/filtron` present, only `src/filtron`

GO version: go1.13.5 linux/amd64

**Comment by Sh3tix** [comment]
Did you find any solution ? I have the same thing

**Comment by FransVeldman** [comment]
Same here. Did anyone found a solution?

**Comment by c-bug** [comment]
Just ran in this problem, too.

Go 1.13.5 is too old, try 1.17, for me 1.17.9 worked.

edit filename in utils/filtron.sh line 44, to go1.17.9.linux-amd64.tar.gz

**Comment by FransVeldman** [comment]
It seems there is not much (if any) support for SearX. I went to SearXNG so I don't need filtron anymore.

**Comment by pyrenaica** [comment]
I  took the advice of running SearXNG which works great, did not know that was a thing.
