### ISSUE TITLE
search request limit is not working

### ISSUE THREAD

**Issue by r4dh4l** [asciimoo/filtron#5]
Hi,

if I set

```
...
        "name": "search request",
        "filters": ["Param:q", "Path=^(/|/search)$"],
        "interval": 60,
        "limit": 1,
...
```

in my `rules.json` I would expect that I can only make 1 search request per minute but actually I can make as much as I want (like without using filtron at all).

Did I understand something wrong?

**Comment by return42** [comment]
> Did I understand something wrong?

No. I had the same issue, after digging a while I realized the `Param:q` is not given in my test scenario.  Testing with:

    curl http://127.0.0.1:4004/?q=foo

filtron works as expected. Can you please repeat your test

@asciimoo I guess we can close this issue.

**Comment by asciimoo** [comment]
Thanks for testing it.

**Comment by r4dh4l** [comment]
> > Did I understand something wrong?
> 
> No. I had the same issue, after digging a while I realized the `Param:q` is not given in my test scenario. Testing with:
> 
> ```
> curl http://127.0.0.1:4004/?q=foo
> ```
> 
> filtron works as expected. Can you please repeat your test

Okay but why do I need to provide a parameter so that filtron works? Users won't search by providing `?q=foo`, will they?

**Comment by return42** [comment]
> Okay but why do I need to provide a parameter so that filtron works? Users won't search by providing ?q=foo, will they?

Are you trolling me? .. You set this in your filtron.rules, compare with your initial post:

    "filters": ["Param:q", ....

BTW the searx API: https://asciimoo.github.io/searx/dev/search_api.html

**Comment by r4dh4l** [comment]
> > Okay but why do I need to provide a parameter so that filtron works? Users won't search by providing ?q=foo, will they?
> 
> Are you trolling me? .. You set this in your filtron.rules, compare with your initial post:
> 
> ```
> "filters": ["Param:q", ....
> ```
> 
> BTW the searx API: https://asciimoo.github.io/searx/dev/search_api.html

Yes, I've set this - according to copypasting what I've read in https://asciimoo.github.io/searx/admin/filtron.html#sample-configuration-of-filtron. So my expectation was that if I set

```
[{
   "name":"search request",
   "filters":[
      "Param:q",
      "Path=^(/|/search)$"
   ],
   "interval":"<time-interval-in-sec (int)>",
   "limit":"<max-request-number-in-interval (int)>",
   "subrules":[
      {
         "name":"roboagent limit",
         "interval":"<time-interval-in-sec (int)>",
         "limit":"<max-request-number-in-interval (int)>",
         "filters":[
            "Header:User-Agent=(curl|cURL|Wget|python-requests|Scrapy|FeedFetcher|Go-http-client)"
         ],
         "actions":[
            {
               "name":"block",
               "params":{
                  "message":"Rate limit exceeded"
               }
            }
         ]
      },
      {
         "name":"botlimit",
         "limit":0,
         "stop":true,
         "filters":[
            "Header:User-Agent=(Googlebot|bingbot|Baiduspider|yacybot|YandexMobileBot|YandexBot|Yahoo! Slurp|MJ12bot|AhrefsBot|archive.org_bot|msnbot|MJ12bot|SeznamBot|linkdexbot|Netvibes|SMTBot|zgrab|James BOT)"
         ],
         "actions":[
            {
               "name":"block",
               "params":{
                  "message":"Rate limit exceeded"
               }
            }
         ]
      },
      {
         "name":"IP limit",
         "interval":"<time-interval-in-sec (int)>",
         "limit":"<max-request-number-in-interval (int)>",
         "stop":true,
         "aggregations":[
            "Header:X-Forwarded-For"
         ],
         "actions":[
            {
               "name":"block",
               "params":{
                  "message":"Rate limit exceeded"
               }
            }
         ]
      },
      {
         "name":"rss/json limit",
         "interval":"<time-interval-in-sec (int)>",
         "limit":"<max-request-number-in-interval (int)>",
         "stop":true,
         "filters":[
            "Param:format=(csv|json|rss)"
         ],
         "actions":[
            {
               "name":"block",
               "params":{
                  "message":"Rate limit exceeded"
               }
            }
         ]
      },
      {
         "name":"useragent limit",
         "interval":"<time-interval-in-sec (int)>",
         "limit":"<max-request-number-in-interval (int)>",
         "aggregations":[
            "Header:User-Agent"
         ],
         "actions":[
            {
               "name":"block",
               "params":{
                  "message":"Rate limit exceeded"
               }
            }
         ]
      }
   ]
}]
```

limitations will be according to what is written as explanation:

> An example configuration can be find below. This configuration limits the access of:
> - scripts or applications (roboagent limit)
> - webcrawlers (botlimit)
> - IPs which send too many requests (IP limit)
> - too many json, csv, etc. requests (rss/json limit)
> - the same UserAgent of if too many requests (useragent limit)

If "the same UserAgent of if too many requests (useragent limit)" does not mean that someone is limited in searching 20 times per minute the same term than I'm sorry for my limited "mental capacity".

However: No, I was not trolling you and I don't understand why you react like this and even more I don't understand why @asciimoo reacts with laughing. The reaction of both of you seems a little bit arrogant since I was just kindly asking if I understood something wrong opening this issue.

**Comment by return42** [comment]
> The reaction of both of you seems a little bit arrogant since I was just kindly asking if I understood something wrong opening this issue.

Sorry this was not our intention. But you also have to be a little more attentive before posting! .. see what you have done again with your rashly C&P.

```json
[{
   "name":"search request",
   "filters":[
      "Param:q",
      "Path=^(/|/search)$"
   ],
   "interval":"<time-interval-in-sec (int)>",
   "limit":"<max-request-number-in-interval (int)>",
```

.. you did not replaced the '<...>' placeholder.  There is zero knowledge needed to find the mistake.

So please don't be offended, instead work thoroughly and check what you have done before you ask rash questions to the community.

**Comment by r4dh4l** [comment]
> Sorry this was not our intention.

Accepted, I appreciate your reply.

> But you also have to be a little more attentive before posting! .. see what you have done again with your rashly C&P.

You are right, of course I've adjusted the placeholders in my personal config from begin on which is:

```
[
    {
        "_comment": "vi /usr/local/filtron/rules.json",
        "_comment": "If you change something in this file don't forget to restart filtron",
        "_comment": "systemctl restart filtron.service && systemctl status filtron.service",
        "_comment": "systemctl restart uwsgi.service && systemctl status uwsgi.service",
        
        "name": "search request",
        "filters": ["Param:q", "Path=^(/|/search)$"],
        "interval": 60,
        "limit": 60,
        "subrules": [
            {
                "name": "roboagent limit",
                "interval": 60,
                "limit": 5,
                "filters": ["Header:User-Agent=(curl|cURL|Wget|python-requests|Scrapy|FeedFetcher|Go-http-client)"],
                "actions": [
                    {"name": "block",
                     "params": {"message": "Rate limit exceeded"}}
                ]
            },
            {
                "name": "botlimit",
                "limit": 0,
                "stop": true,
                "filters": ["Header:User-Agent=(Googlebot|bingbot|Baiduspider|yacybot|YandexMobileBot|YandexBot|Yahoo! Slurp|MJ12bot|AhrefsBot|archive.org_bot|msnbot|MJ12bot|SeznamBot|linkdexbot|Netvibes|SMTBot|zgrab|James BOT)"],
                "actions": [
                    {"name": "block",
                     "params": {"message": "Rate limit exceeded"}}
                ]
            },
            {
                "name": "IP limit",
                "interval": 60,
                "limit": 60,
                "stop": true,
                "aggregations": ["Header:X-Forwarded-For"],
                "actions": [
                    {"name": "block",
                     "params": {"message": "Rate limit exceeded"}}
                ]
            },
            {
                "name": "rss/json limit",
                "interval": 60,
                "limit": 5,
                "stop": true,
                "filters": ["Param:format=(csv|json|rss)"],
                "actions": [
                    {"name": "block",
                     "params": {"message": "Rate limit exceeded"}}
                ]
            },
            {
                "name": "useragent limit",
                "interval": 60,
                "limit": 5,
                "aggregations": ["Header:User-Agent"],
                "actions": [
                    {"name": "block",
                     "params": {"message": "Rate limit exceeded"}}
                ]
            }
        ]
    }
]
```

My point was: I copy&pasted the config "stucture" and didn't create an own one.

> So please don't be offended, instead work thoroughly and check what you have done before you ask rash questions to the community.

After explaining that I didn't copy&paste the placeholders: Is it still "rash" to ask if my expectation from the first post...

> I would expect that I can only make 1 search request per minute but actually I can make as much as I want (like without using filtron at all).

...is wrong? Just to clarify: "Search request" for me is what a user searches using the search bar (not via URL parameters).

**Comment by return42** [comment]
> After explaining that I didn't copy&paste the placeholders:

How am I supposed to smell that? Definitely, you are trolling me!

> ...is wrong? Just to clarify: "Search request" for me is what a user searches using the search bar (not via URL parameters).

Do you know HTTP GET and POST?

Setting up a HTTP filter needs some basic knowledge about the used technologies.  It is not an easy task that can be done by anyone who knows where the power button of the PC is.

We at searx know this, that's why we are on the way to simplify such setups (https://github.com/asciimoo/searx/pull/1803 is in work for this).

Since this issue is not an filtron error nor a filtron question is I am asking @asciimoo to close this issue.

I am out!

**Comment by r4dh4l** [comment]
> How am I supposed to smell that? Definitely, you are trolling me!

If any kind of mistake users do is automatically "trolling" for you, you are right, but let me say: I'm not an educated "fulltime admin", just someone with a certain "IT curiosity" trying to be less "usance" for IT monopolists and be more "user" again in my freetime. If people like me are some kind of annoyance for you I'm very sorry, it was not my intention to bother anyone with my questions here. I just tried to learn and understand what I do wrong.

> Do you know HTTP GET and POST?

Actually not but I will try to learn the difference now.

> Setting up a HTTP filter needs some basic knowledge about the used technologies. It is not an easy task that can be done by anyone who knows where the power button of the PC is.

So maybe I'm just not in the target group of Searx. That's okay, I think it was worth trying it since I didn't manage to host [YaCy](https://yacy.net/) in stable way.

> Since this issue is not an filtron error nor a filtron question is I am asking @asciimoo to close this issue.

It was already closed [here](https://github.com/asciimoo/filtron/issues/5#issuecomment-573647573).

> I am out!

Although we were somehow not able to talk on the same "level" let me thank you anyway for your replies, even though it makes me sad that you were accusing me trolling (to underline it again: That was not my intention at any time, by all means not in the way how I understand "trolling").
