### ISSUE TITLE
Any changes with v0.1.0?

### ISSUE THREAD

**Issue by r4dh4l** [asciimoo/filtron#9]
Hi,

I'm used to send me update notifications via RSS over blogtrottr.com but for https://github.com/asciimoo/filtron/releases/tag/v0.1.0 "No content." is written as description. So I'm a little bit confused: Were there any changes with v0.1.0 or is it just the current development state tagged as "release"?

**Comment by asciimoo** [comment]
It is just a tag and binaries of the current master.
